version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: backend-db
    ports:
     - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=demo
      - POSTGRES_DB=backend

volumes:
  postgres:
    name: backend