version: '3.8'
services:
  app:
    container_name: backend-2023
    image: backend-2023
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3030:3030
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    restart: unless-stopped
    environment:
      - NODE_ENV=dev
      - PORT=3030
      - DATABASE_URL=backend-db
  postgres:
    image: postgres:14
    container_name: backend-db
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=demo
      - POSTGRES_DB=backend
volumes:
  postgres:
    name: backend
